INTYGFV-16023: Implemented service to handle request to intyg proxy service for getCareProviderOfCareUnit
sklintyg/infra pull request #209
Opened 2023-10-31 14:40 UTC by mikaelaromild1

2023-11-01 15:00 UTC, mww-sopra-steria requested changes
Nice! A few comments to look at though!

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/client/HsaIntygProxyServiceCareProviderOfCareUnitClient.java
> +public class HsaIntygProxyServiceCareProviderOfCareUnitClient {
This client will be reused any time we want to get a HealthCareUnit. Change the name to HsaIntygProxyServiceHealthCareUnitClient

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/client/HsaIntygProxyServiceCareProviderOfCareUnitClient.java
> +    private String careProviderOfCareUnitEndpoint;
Rename to healthCareUnitEndpoint

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/client/HsaIntygProxyServiceCareProviderOfCareUnitClient.java
> +    public GetCareProviderOfCareUnitResponseDTO getCareProviderOfCareUnit(
Rename method to getHealthCareUnit(...)

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/dto/GetCareProviderOfCareUnitResponseDTO.java
> +public class GetCareProviderOfCareUnitResponseDTO {
Rename to HealthCareUnitResponseDTO

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/dto/GetCareProviderOfCareUnitRequestDTO.java
> +public class GetCareProviderOfCareUnitRequestDTO {
Rename to HealthCareUnitRequestDTO

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/constants/HsaIntygProxyServiceConstants.java
> +    public static final String CARE_PROVIDER_OF_CARE_UNIT_CACHE_NAME = "hsaIntygProxyServiceCareProviderOfCareUnitCache";
Rename to HEALTH_CARE_UNIT_CACHE_NAME = "hsaIntygProxyServiceHealthCareUnitCache"

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/dto/GetCareProviderOfCareUnitRequestDTO.java
> +    String careUnitHsaId;
Rename member to hsaId so it matches the api in intyg-proxy-service

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/HsaLegacyIntegrationOrganizationService.java
> +            log.warn("HsaServiceCallException thrown: {}", hsaServiceCallException);
Consider changing the log message to something more descriptive e.g. "Could fetch health care unit".

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/GetCareProviderOfCareUnitService.java
> +public class GetCareProviderOfCareUnitService {
Rename to GetHealthCareUnitService

2023-11-01 15:00 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/GetCareProviderOfCareUnitService.java
> +    public String get(GetCareProviderOfCareUnitRequestDTO getCareProviderOfCareUnitRequestDTO) throws HsaServiceCallException {
Should return HealthCareUnit.

2023-11-02 09:37 UTC, mikaelaromild1 commented
Thanks for the comments! I have made the requested changes :)

2023-11-02 11:39 UTC, mww-sopra-steria requested changes
Noticed a few more places where naming needs to be updated. Also important that the cache-annotation is correct now when naming has changed.

2023-11-02 11:39 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/configuration/CacheConfiguration.java
> +    public Cache hsaIntygProxyServiceCareProviderOfCareUnitCache() {
Call this hsaIntygProxyServiceHealthCareUnitCache()

2023-11-02 11:39 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/configuration/CacheConfiguration.java
> +    private String hsaCareProviderOfCareUnitCacheExpirySeconds;
Call this hsaHealtCareUnitCacheExpirySeconds.

2023-11-02 11:39 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/configuration/CacheConfiguration.java
> +    private String hsaHealthUnitMembersCacheExpirySeconds;
Call this hsaHealtCareUnitMembersCacheExpirySeconds.

2023-11-02 11:39 UTC, mww-sopra-steria commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/GetHealthCareUnitService.java
> +    @Cacheable(cacheNames = HEALTH_CARE_UNIT_CACHE_NAME, key = "#getCareProviderOfCareUnitRequestDTO.careUnitHsaId",
change #getCareProviderOfCareUnitRequestDTO.careUnitHsaId to #getHealthCareUnitRequestDTO.hsaId

2023-11-02 13:49 UTC, mww-sopra-steria approved these changes
Approved! :-)

2023-11-02 13:54 UTC, merged