INTYGFV-16158: Implemented getAuthorizedEnheterForHosPerson
sklintyg/infra pull request #224
Opened 2023-11-30 15:11 UTC by mhornfeldt

2023-12-01 14:30 UTC, ChrilleSigerhed requested changes
Tested to review from Intellij, kinda neat.

VERY impressive, superb work.

Only got a few minor comments to consider.

Note: I think we also will be able to clarify wich services will return null/empty responses on monday. So maybe some more changes will be needed if we for example change the response from getHealthCareUnitMembersFromHsa().

2023-12-01 14:30 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +        final var isUnitDefined = unit.getUnitHsaId() != null && !unit.getUnitHsaId().isEmpty();
Since we changed so that unit returns null if not found, this check will cause a NullPointerException.

Maybe getUnitFromHsa should return an Optional of nullable that we can check instead?

2023-12-01 15:36 UTC, mhornfeldt commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/converter/UserCredentialListConverter.java
> +        final var firstCredential = credentialInformation.isEmpty() ? null : credentialInformation.get(0);
Oh okay. I can look into this but weird behaviour indeed

2023-12-01 15:37 UTC, mhornfeldt commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +        final var isUnitDefined = unit.getUnitHsaId() != null && !unit.getUnitHsaId().isEmpty();
I didn't know it was changed in infra but I can update it

2023-12-04 08:00 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/converter/UserCredentialListConverter.java
> +        final var firstCredential = credentialInformation.isEmpty() ? null : credentialInformation.get(0);
Our testdata does not reflect this behaviour, so its hard to tell. If we would assume the actual data looks like our testdata, this list always has only one element. In that case, using the firstCredential seems reasonable.

2023-12-04 09:11 UTC, merged