INTYGFV-16142: Implemented legacy getVardenhet
sklintyg/infra pull request #225
Opened 2023-11-30 17:57 UTC by mikeyOne

Will require addition of field telephoneNumber to Unit object in intyg-proxy-service

2023-12-01 09:40 UTC, ChrilleSigerhed requested changes
Awsome, great work! Left some comments to consider.

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +        try {
I like what you did for getUnit, and am suggesting we try to handle the error the same way in this method.

Instead maybe we should update GetHealthCareUnitMembersService:
```java
     @Cacheable(cacheNames = HEALTH_CARE_UNIT_MEMBERS_CACHE_NAME, key = "#getHealthCareUnitMembersRequest.hsaId",
        unless = "#result == null")
    public HealthCareUnitMembers get(GetHealthCareUnitMembersRequestDTO getHealthCareUnitMembersRequest) {
        validateRequest(getHealthCareUnitMembersRequest.getHsaId());
        final var healthCareUnitMembersResponse = healthCareUnitMembersClient.getHealthCareUnitMembers(getHealthCareUnitMembersRequest);
        if (healthCareUnitMembersResponse.getHealthCareUnitMembers() == null) {
            log.warn("Failure fetching HealthCareUnitMembers for unit with id '{}'.", getHealthCareUnitMembersRequest.getHsaId());
        }
        return healthCareUnitMembersResponse.getHealthCareUnitMembers();
    }
```
This would require an update in intyg-proxy-service, since it currently returns a empty object if not found.

And update ```getUnitMembers``` to something like this:
```java
  final var unitMemberRequest = GetHealthCareUnitMembersRequestDTO.builder().hsaId(hsaId).build();  
  return Optional.ofNullable(getHealthCareUnitMembersService.get(unitMemberRequest));
```

Im you agree, feel free to update intyg-proxy-service aswell!

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            careUnit.setEpost(unit.getMail());
Do you think this logic should be moved into some kind of decorator? Im thinking something like DecorateCareUnitService. That would make the purpose of this service clearer in my opinion, and leave the decoration of careUnit to another service.

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            final var unit = getUnit(hsaId).orElseThrow();
I think it would be a good idea to handle the exception here instead. Something like:

```java
final var unit = getUnit(hsaId).orElseThrow(
            () -> new WebServiceException(String.format("Could not get unit with hsaId '%s'", hsaId))
        );
```

We dont need to log this event, since that is handled by getUnitService.

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyIntegrationOrganizationService.java
> +        return hsaLegacyGetCareUnitService.get(vardenhetHsaId);
Consider wrapping this in a DTO with @Value annotation. I think its a good pattern that our services only handle immutable-objects!

```java
    @Override
    public Vardenhet getVardenhet(String vardenhetHsaId) {
        return hsaLegacyGetCareUnitService.get(
            GetCareUnitRequestDTO.builder()
                .hsaId(vardenhetHsaId)
                .build()
            );
    }
```

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/test/java/se/inera/intyg/infra/integration/intygproxyservice/services/HsaLegacyIntegrationOrganizationServiceTest.java
> +        void shouldCallHsaLegacyGetCareUnitService() {
Should we verify that the response if as expected aswell?

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/build.gradle
> -    testRuntimeOnly "org.slf4j:slf4j-simple"
Is this needed?

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +                careUnit.setMottagningar(getUnits(members, careUnit));
Would it be a good idea to change ```getUnits(members, careUnit)``` to ```getSubUnits(members, careUnit)``` ?

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            .map(member -> createUnit(member, careUnit))
Would it be a good idea to change ```createUnit(members, careUnit)``` to ```createSubUnit(members, careUnit)``` ?

2023-12-01 09:40 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +    private Mottagning newUnit(HealthCareUnitMember member) {
Should this be ```newSubUnit```?

2023-12-01 13:29 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/build.gradle
> -    testRuntimeOnly "org.slf4j:slf4j-simple"
It causes the below red warning when running tests in intellij since  two logger implementations are found on classpath. Logback-classic has since been added as implementation dependency in root build.gradle so no need of having slf4j-simple added specifically in this module.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/mheglind/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.12/d4dee19148dccb177a0736eb2027bd195341da78/logback-classic-1.2.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/mheglind/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/a41f9cfe6faafb2eb83a1c7dd2d0dfd844e2a936/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

2023-12-12 22:20 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyIntegrationOrganizationService.java
> +        return hsaLegacyGetCareUnitService.get(vardenhetHsaId);
done

2023-12-12 22:20 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/test/java/se/inera/intyg/infra/integration/intygproxyservice/services/HsaLegacyIntegrationOrganizationServiceTest.java
> +        void shouldCallHsaLegacyGetCareUnitService() {
done

2023-12-12 22:22 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +                careUnit.setMottagningar(getUnits(members, careUnit));
Tests with names including subunit has been removed. Musch logic has been moved to other classes.

2023-12-12 22:22 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +    private Mottagning newUnit(HealthCareUnitMember member) {
has been removed

2023-12-12 22:23 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            .map(member -> createUnit(member, careUnit))
this has been moved an renamed

2023-12-12 22:30 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            careUnit.setEpost(unit.getMail());
code in this section now largely uses logic from other classes

2023-12-12 22:32 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +        try {
moved

2023-12-12 22:33 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +        try {
was this done by someone else

2023-12-12 22:36 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            final var unit = getUnit(hsaId).orElseThrow();
nothing is logged if 500 from intyg-proxy-service.

2023-12-13 08:56 UTC, ChrilleSigerhed requested changes
Great job, added some minor comments to consider that I think would improve the quality of the code.

2023-12-13 08:56 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +    public Vardenhet get(GetUnitRequestDTO unitRequest, GetHealthCareUnitMembersRequestDTO unitMembersRequest) {
Should we use vardenhetHsaId instead and use the provided functions to create our DTOs? 

We could also validate that the vardgivarId was provided, and if not, throw an IllegalArgumentException.

2023-12-13 08:56 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +        final var unit = getUnitFromHsa(unitRequest);
I think we should use the already defined getUnitFromHsa, and instead add the throw to the method:

```java
        final var unit = getUnitFromHsa(unitRequest.getHsaId()).orElseThrow(WebServiceException::new);
```

Then we also get rid of the extra log, wich already happends in ```getUnitService.get```

2023-12-13 08:56 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +        final var members = getHealthCareUnitMembersFromHsa(unitMembersRequest);
I think we can use the already defined getHealthCareUnitMembersFromHsa, and instead handle the affected logic in the converter.

2023-12-13 08:56 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/converter/CareUnitConverter.java
> +        optionalUnitMembers.ifPresent(members -> {
If we use the already defined getHealthCareUnitMembers, we just use the provided functions for this, since we already handle null checks/empty in them.

```java
    public Vardenhet convert(Unit unit, HealthCareUnitMembers unitMembers) {
        final var careUnit = new Vardenhet(unit.getUnitHsaId(), unit.getUnitName(), unit.getUnitStartDate(), unit.getUnitEndDate());
        final var postalAddress = unit.getPostalAddress();
        final var telephoneNumber = unit.getTelephoneNumber();

        careUnit.setMottagningar(getCareUnitMembers(unitMembers, careUnit.getId(), AgandeForm.OKAND));
        careUnit.setArbetsplatskod(getWorkplaceCode(unitMembers.getHealthCareUnitPrescriptionCode()));
        .....
       
```

2023-12-13 08:56 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +    private Unit getUnitFromHsa(GetUnitRequestDTO unitRequest) {
Could be removed

2023-12-13 08:56 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +    private Optional<HealthCareUnitMembers> getHealthCareUnitMembersFromHsa(GetHealthCareUnitMembersRequestDTO unitMemberRequest) {
Could be removed

2023-12-13 11:42 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/HsaLegacyGetCareUnitService.java
> +            final var unit = getUnit(hsaId).orElseThrow();
If that event should occur, maybe we can let that exception run all the way, and be handled by the services that uses the service?

2023-12-14 09:53 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +    public Vardenhet get(GetUnitRequestDTO unitRequest, GetHealthCareUnitMembersRequestDTO unitMembersRequest) {
done

2023-12-14 09:54 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +        final var unit = getUnitFromHsa(unitRequest);
done

2023-12-14 09:54 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +        final var members = getHealthCareUnitMembersFromHsa(unitMembersRequest);
done

2023-12-14 09:54 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/converter/CareUnitConverter.java
> +        optionalUnitMembers.ifPresent(members -> {
done

2023-12-14 09:54 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +    private Unit getUnitFromHsa(GetUnitRequestDTO unitRequest) {
done

2023-12-14 09:54 UTC, mikeyOne commented on integration/hsa-integration-intyg-proxy-service/src/main/java/se/inera/intyg/infra/integration/intygproxyservice/services/organization/GetCareUnitService.java
> +    private Optional<HealthCareUnitMembers> getHealthCareUnitMembersFromHsa(GetHealthCareUnitMembersRequestDTO unitMemberRequest) {
done

2023-12-14 10:02 UTC, ChrilleSigerhed approved these changes
Well done! Left some comments to consider before merging!

2023-12-14 11:19 UTC, merged