INTYGFV-16183: Implemented integration from infra to intyg-proxy-service for handleHospCertificationPersonResponseType
sklintyg/infra pull request #232
Opened 2023-12-11 09:36 UTC by mikaelaromild1

2023-12-11 10:10 UTC, ChrilleSigerhed requested changes
Nice, added some comments to consider.

2023-12-11 10:10 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/test/java/se/inera/intyg/infra/integration/intygproxyservice/client/authorization/HsaIntygProxyServiceHospCertificationPersonClientTest.java
> +class HsaIntygProxyServiceHospCertificationPersonClientTest {
Would be nice if we could add a test that also verifies that we handle the IllegalStateException.

2023-12-11 10:10 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/test/java/se/inera/intyg/infra/integration/intygproxyservice/services/authorization/GetHospCertificationPersonServiceTest.java
> +    void shouldValidateRequest() {
When we validate multiple parameters, it might be a good idea to test them individually. Something like:

```shouldThrowIfPersonIdIsNull``` 
```shouldThrowIfPersonIdIsEmpty```
```shouldThrowIfCertificationIdIsNull``` 
```shouldThrowIfCertificationIdIsEmpty```

These tests could be placed in a "@Nested"-class to separate them from the rest of the test logic.

2023-12-11 10:10 UTC, ChrilleSigerhed commented on integration/hsa-integration-intyg-proxy-service/src/test/java/se/inera/intyg/infra/integration/intygproxyservice/services/authorization/GetHospCertificationPersonServiceTest.java
> +        RESULT.setResultText(RESULT_TEXT);
If we wanna use a static final parameter for result, I suggest we build it completly in our setup.

2023-12-11 15:10 UTC, mhornfeldt approved these changes
Nice!

2023-12-12 07:07 UTC, ChrilleSigerhed approved these changes

2023-12-12 07:16 UTC, merged